{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.kubedoop.dev
  resources:
  - s3buckets
  - s3connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubedoop.dev
  resources:
  - hivemetastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubedoop.dev
  resources:
  - hivemetastores/finalizers
  verbs:
  - update
- apiGroups:
  - kubedoop.dev
  resources:
  - hivemetastores/status
  verbs:
  - get
  - patch
  - update
{{- end }}
